
function keyhandler(event){
	switch(event.which){
		case 8 :  console.log({'key':event.key}); break;
		case 9 :  console.log({'key':event.key}); break;
		case 13 : console.log({'key':event.key}); break;
		case 27 : console.log({'key':event.key}); break;
		case 32 : console.log({'key':event.key}); break;
		case 33 : console.log({'key':event.key}); break;
		case 34 : console.log({'key':event.key}); break;
		case 35 : console.log({'key':event.key}); break;
		case 36 : console.log({'key':event.key}); break;
		case 37 : console.log({'key':event.key}); break;
		case 38 : console.log({'key':event.key}); break;
		case 39 : console.log({'key':event.key}); break;
		case 40 : console.log({'key':event.key}); break;
		case 46 : console.log({'key':event.key}); break;
		case 65 : console.log({'key':event.key}); break;
		case 66 : console.log({'key':event.key}); break;
		case 67 : console.log({'key':event.key}); break;
		case 68 : console.log({'key':event.key}); break;
		case 69 : console.log({'key':event.key}); break;
		case 70 : console.log({'key':event.key}); break;
		case 71 : console.log({'key':event.key}); break;
		case 72 : console.log({'key':event.key}); break;
		case 73 : console.log({'key':event.key}); break;
		case 74 : console.log({'key':event.key}); break;
		case 75 : console.log({'key':event.key}); break;
		case 76 : console.log({'key':event.key}); break;
		case 77 : console.log({'key':event.key}); break;
		case 78 : console.log({'key':event.key}); break;
		case 79 : console.log({'key':event.key}); break;
		case 80 : console.log({'key':event.key}); break;
		case 81 : console.log({'key':event.key}); break;
		case 82 : console.log({'key':event.key}); break;
		case 83 : console.log({'key':event.key}); break;
		case 84 : console.log({'key':event.key}); break;
		case 85 : console.log({'key':event.key}); break;
		case 86 : console.log({'key':event.key}); break;
		case 87 : console.log({'key':event.key}); break;
		case 88 : console.log({'key':event.key}); break;
		case 89 : console.log({'key':event.key}); break;
		case 90 : console.log({'key':event.key}); break;
		case 57 : console.log({'key':event.key}); break;
		case 56 : console.log({'key':event.key}); break;
		case 55 : console.log({'key':event.key}); break;
		case 54 : console.log({'key':event.key}); break;
		case 53 : console.log({'key':event.key}); break;
		case 52 : console.log({'key':event.key}); break;
		case 51 : console.log({'key':event.key}); break;
		case 50 : console.log({'key':event.key}); break;
		case 4 :  console.log({'key':event.key});break;
		default : console.log({'key':event.key}); break;                    
	}	
};
